### ISSUE TITLE
Disqus [Question]

### ISSUE THREAD

**Issue by smaragdus** [bjornstar/intercept-redirect#27]
@bjornstar 

Hello,

When I open a link posted in Disqus comments in stead of the actual URL, for example:

`https://99endof.blogspot.com/2021/08/beyond-covid-level-zero-lies-asylum.html`

I got this one:

`https://99endof.blogspot.com/2021/08/beyond-covid-level-zero-lies-asylum.html:87dEAGWueUX1QRsoG2xFdXJaVag`

So I have to manually edit the URL (deleting `:87dEAGWueUX1QRsoG2xFdXJaVag` part) to land on the actual page and not on a 404 page.

Is [Intercept Redirect](https://github.com/bjornstar/intercept-redirect) supposed to remove this:

`:87dEAGWueUX1QRsoG2xFdXJaVag`

I have tried different URL cleaners/strippers but so far I have not found an extension which cleans these types of Disqus URLs.

If [Intercept Redirect](https://chrome.google.com/webstore/detail/intercept-redirect/kdjmiebhgaleboaamnehjbamlghkoedf) is not supposed to clean such URLs, can the developer recommend an extension which can do this job?

Regards

**Comment by bjornstar** [comment]
It's supposed to strip that part of the URL. Could you give me a link to the page that has the redirect url on it?

**Comment by smaragdus** [comment]
@bjornstar 

Thanks for the quick response.

[Link](https://www.breitbart.com/europe/2021/08/06/vaccines-for-ever-more-to-travel-abroad-says-uk-govt-transport-minister/#comment-5483880354) to the comment containing the link quoted above.

**screen:**

![Breitbart - 2021-08-07 - 003](https://user-images.githubusercontent.com/9025757/128585439-45c7ed74-841c-466a-a891-2c5addfdd6f1.png)

But actually I got these types of links in every posted link in comments in Disqus.

**Comment by bjornstar** [comment]
Ah, I thought you were reporting a bug. Intercept Redirect does support `disqus` and trims off the part of the URL that would break it.

**Comment by smaragdus** [comment]
@bjornstar 

But this part of the URL:

`:87dEAGWueUX1QRsoG2xFdXJaVag`

does not get trimmed, right?

**Comment by bjornstar** [comment]
> @bjornstar
> 
> But this part of the URL:
> 
> `:87dEAGWueUX1QRsoG2xFdXJaVag`
> 
> does not get trimmed, right?

It does trim that part of the URL when doing an internal redirect. Did you try using the extension?

**Comment by smaragdus** [comment]
@bjornstar 

> Did you try using the extension?

I installed it several times and as it did not have neither options nor context menu integration I supposed the trimming was done automatically.

Thanks
