### ISSUE TITLE
google shopping redirect to "clickserve.dartsearch.net"

### ISSUE THREAD

**Issue by freeocha** [bjornstar/intercept-redirect#28]
Instead of redirect to "www.googleadservices.com", google shopping sometime redirect to "clickserve.dartsearch.net". for example:
https://www.google.com/search?q=Logitech+K375S&newwindow=1&source=lnms&tbm=shop&sa=X&ved=2ahUKEwiq3sTEvbHzAhWT6Z4KHaVWD_0Q_AUoAnoECAEQBA&biw=1920&bih=969&dpr=1
If you are in the US (or you could use VPN), you should see the third link on top, which is a link for Newegg.
It will firstly redirect to:
https://www.google.com/aclk?sa=l&ai=DChcSEwjB9r_GvbHzAhU7H60GHVMrD6wYABAHGgJwdg&sig=AOD64_1ua3MpVOHz8bN8c2nZALUnmqyb8w&ctype=5&q=&ved=0ahUKEwidubvGvbHzAhWOFTQIHRroC9AQww8IjAU&adurl=
And then:
https://clickserve.dartsearch.net/link/click?lid=92700046663456130&ds_s_kwgid=58700005237799092&ds_s_inventory_feed_id=97700000001004293&ds_a_cid=259782&ds_a_caid=2084573495&ds_a_agid=76322017669&ds_a_fiid=&ds_a_lid=pla-806444387973&ds_a_extid=&ds_e_adid=375267988025&ds_e_product_group_id=806444387973&ds_e_product_id=N82E16823126391&ds_e_product_merchant_id=8438988&ds_e_product_country=US&ds_e_product_language=en&ds_e_product_channel=online&ds_e_product_store_id=&ds_e_ad_type=pla&ds_url_v=2&ds_dest_url=https://www.newegg.com/logitech-k375s-multi-device-wireless-keyboard-and-stand-combo-920-008165-bluetooth-wireless/p/N82E16823126391?item=N82E16823126391&source=region&nm_mc=knc-googleadwords-pc&cm_mmc=knc-googleadwords-pc-_-pla-_-keyboards-_-N82E16823126391&gclsrc=aw.ds&

**Comment by bjornstar** [comment]
We can totally skip the `clickserve.dartsearch.net` redirect, thanks for suggesting it!

**Comment by bjornstar** [comment]
Sorry it took a while it's been a very busy month for me. I just published `v8.2.0` on all browser addon sites today. It may take a little bit for all the approvals to go through, but it should be available soon. Thanks again for your feedback!
