### ISSUE TITLE
safelinks.protection.outlook.com

### ISSUE THREAD

**Issue by bjornstar** [bjornstar/intercept-redirect#47]
https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbjornstar.com&sdata=iBgRIDHzH7S58MOE1kndjxBtQhSTS1M9D30aaSIVyag%3D&reserved=0

Should probably just grab all subdomains of safelinks.

**Comment by zeridon** [comment]
Check: https://github.com/phavekes/unmangleOutlookSafelinks/blob/master/src/display.js

Short story: yes
