### ISSUE TITLE
Unmangle Microsoft teams safelinks

### ISSUE THREAD

**Issue by zeridon** [bjornstar/intercept-redirect#49]
Microsoft teams also does "Safe Links". Please add support for unmangling/unredirecting that protection too

Sample:
`https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html?url=https%3A%2F%2Fnoise.getoto.net&locale=en-us&dest=https%3A%2F%2Fteams.microsoft.com%2Fapi%2Fmt%2Femea%2Fbeta%2Fatpsafelinks%2Fgeturlreputationsitev2%2F&pc=L2UQGmwbBfE3rd%252bb9pkjYCeIDaV3ufN9ovnqtBjKupUVDraXAqPXQsykbobKwdyIZIbCrFky1V6e%252fCm99qFLC1SwlUzObPntDsRUmiNCzQbwTggAYFlOQl%252f57D%252b2DztSkH18V9DpGs693KmjPLbSb%252fICq0%252fcGDcjHX2tYbwGRmQFUz5Gn2xBpBf5%252buEx6OhSogGitpSSL50204FAB9KeD1zIJXK872n2v6NPWXtRT43rMxBK4ISROR1N6dhANnaCBrBo4k%252fG3QwtRI%252fxSb38hwRfFav9DQ9g0zKMLEppSXzH6W4Zt9ZbbwhlewGXRm1DYzS56GTGN%252bb4cVv7qrzRwf6ilSMs6n0szotc0qG9BuEAEzlKyBnrnLPWoMtqCN6X7oz9Qr6NXPPlc273qKbOArsBW%252b0PBmhbHRh%252fwfChcMDUu67Ofb5U4aeIFBn1JQs8HgBRae%252bj5k9Ku5xRxKl89pZH5ZUKPjpZu1EtwW2AX0GpAltIzw4vw1gjspikJGYA5BLb20L%252byNUgHKo522Ey69H%252buL60miseoY5XuLioVLxXixHbnc4ugI5SKuc8N%252fQ3HKaIW7GR%252bmpuoFgWY8K04iaf%252fxmhZxeHcuMVo%252bu%252bSnoHgWblkLUWpv67yZgxlC9zlcMWiTRKpJSnm3fA9ffskvuO9Uicy735savKSbGOLkWAtjcCtBMG2siyYjGLaVuCpbpzz3Tc6EROz9v0Pr9xn2xEzUkMtNMgob2NPykHzeqc9PBRo%252fZxWp9KEbrBmCicFOq0Jxl7XOEPdv2iZlaucN5beO3s%252fvWhl6BijqRzbnvxQ1Fy3V0sSsYGKujpfG77r8CojJ2g4MulCLU2Xxa7MvmEFeXTjWW97P3jdowF63Ec%252bEkOLmp2%252f2g1174sksMPbgcoYC8LSVLB1lnZ3YwpDSVvbugofMTpkEg8sQqCQHA%252bM39kv1810orKN8XM5rJ2Qru77v6MHPzChz1ml%252f8JiFO2wikX28DMglfMtq980NuxwinO%252bjVfiOAq29plQ8SULv6mET%252ftxGtXOTR7AmGosvlhia419JaabsBQcXMTXQ6tkyLc64aTP9PFOh%252bDYCV1Jq5W3h9fT0zLyxIxHdk6CIHPp2z2vofDttegyweC58VwoSFpkHrFP%252f5U58d%252bj%252b8QHLb6kheLxTcL2Id9cux72G%252fM2wvpNP7tbdSbPwsdimDvv6yqWL0dSOY0CnHJeJRFqJDHtWRLtCL%252fiuAtO9QRtXQLToroApbVk3nQjtRWiWCIRXEamB823tmC%252bDgNPCWRXoOto0PkR8jW17tiftEKw0YbH12CdGcBE4IR6r%252f3J3RmRR3mYFuGlogJvjrZ9UWwRGc9mgapgmP7ydSy9QnVFPATQMTVa7J4AZHyyZsArnLFgfwWu6verYAZNeFFbEmadOFhImOAgDn0B5kaDZJZRnjaFX4rIAXtBfxWqT6GAhE%253d%3B%20expires%3DFri%2C%2024%20Feb%202023%2006%3A40%3A35%20GMT%3B%20path%3D%2F&wau=https%3A%2F%2FEUR03.safelinks.protection.outlook.com%2FGetUrlReputation&si=1676991667545%3B1676991667545%3B19%3Ac7145705dee048aa85ca2225e75f7be9%40thread.v2&sd=%7BconvId%3A%2019%3Ac7145705dee048aa85ca2225e75f7be9%40thread.v2%2C%20messageId%3A%201676991667545%7D&ce=prod&cv=41%2F23010100913&ssid=4662538d-f64a-91ed-730c-cd3d7af6e25c&ring=general&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0MS8yMzAxMDEwMDkxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ==&bg=%23f0f0f0&fg=%23242424&fg2=%239092c1`

Original URL: https://noise.getoto.net

**Comment by bjornstar** [comment]
That is a monstrous URL 😭 I'll see what I can do.

**Comment by zeridon** [comment]
Monstrous yes :) but still has URL param. The rest is who knows what magic from MS

**Comment by zeridon** [comment]
After some more checking MS teams seems to be using the Office365 safelinks but in XMLHTTPRequest

e.g the flow is:

 * click on link in MS teams
 * On open browser address bar shows: `https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html`
 * Some JS magic happens: `https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp.js?v=10`
 * If valid url, reputation and probably else do JS redirect

The validation logic (on MS side) as far as i can ascertain it is:
 * `isValidDest = isValidTeamsMTUrl(dest);`
 * `isValidUrl = isAllowedHrefProtocol(url);`
 * `if (isValidDest && isValidUrl) http.open("POST", dest, true);`

The rest seems fluff and internal purposes.

Still looking from the code it does indeed seem they are parsing the URI and getting the `url` param that they later feed trough some reputation system.
